# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: cadassignments2025
# "service" is the name of this project. This will also be added to your AWS resource names.
service: aws-http-api-call-app

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com

functions:
  hello:
    handler: handler.reverse
    events:
      - httpApi:
          path: /reverse
          method: post
